### PR TITLE
remove ntp

### PR DESCRIPTION
**Pull request by anulman**

### CODE REVIEW

**Comment by mtrudel** [comment]
ntp is still present in Berksfile{,.lock}

**Comment by anulman** [comment]
knife and berkshelf were throwing ssl errors with their current/previous config. not sure if you'd handle the update differently, but figured i may as well set the first commit :)

**Comment by anulman** [comment]
poke. a bunch of split-out pr's coming your way. let's discuss helpfulness & intent when we meet up?

**Comment by mtrudel** [comment]
There's a lot more than disabling NTP going on here. Can you spilt out the 'general updates to berks / gems / various antique shit that wasn't working' into a separate PR?

**Comment by mtrudel** [comment]
What's up with the update to make postgres listen on localhost? It listens by default on domain sockets, which is both faster and allows for direct user-based auth without passwords.

**Comment by anulman** [comment]
@mtrudel Oop, forgot this PR was opened from my master. Yeah, can split off a couple of PRs soon.

IIRC updates in either PG or Rails-land prohibited domain sockets, will have to parse this back out

**Pull request closed without merging**
